### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by autonome** [aschmahmann/filexp#1]
> 
> % go install github.com/aschmahmann/filexp@latest
> go: downloading github.com/aschmahmann/filexp v0.0.0-20230124204307-6fa7dac93ba7
> go install github.com/aschmahmann/filexp@latest: github.com/aschmahmann/filexp@v0.0.0-20230124204307-6fa7dac93ba7
>         The go.mod file for the module providing named packages contains one or
>         more replace directives. It must not contain directives that would cause
>         it to be interpreted differently than if it were the main module.
>

**Comment by aschmahmann** [comment]
Thanks @autonome. That's what I get for not trying that out myself. Apparently there's a fun issue with Go https://github.com/aschmahmann/filexp/pull/2#issue-1610211705. So for now we've got to clone the repo and build from there 😢.
